# Generated by Django 5.0.3 on 2024-03-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ('pk',)},
        ),
    ]
